spring:
  datasource:
        name: test
        url: jdbc:mysql://47.96.95.15:3306/xhs_law?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: njw19920905
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 500
        initialSize: 1
        maxWait: 4000000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 4800000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false    
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        tomcat:
          test-while-idle: true
          test-on-borrow: true
          time-between-eviction-runs-millis: 3600000
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  output:
    ansi:
      enabled: always
    
server:
  port: 8090
